[package]
name = "trunk_inline_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_toml = "0.19.2"
html5ever = "0.27.0"
markup5ever_rcdom = "0.3.0"
serde = "1.0.198"
toml = "0.8.12"
